"""
Barrel file for observability-engineer skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "observability-engineer"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/observability-engineer"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
