"""
Barrel file for web-command-center skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "web-command-center"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/web-command-center"

# Script modules
# from .scripts.generate_ui import *
# from .scripts.server import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
