"""
Barrel file for self-correction-pilot skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "self-correction-pilot"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/self-correction-pilot"

# Script modules
# from .scripts.watchdog import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
