"""
Barrel file for devops-troubleshooter skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "devops-troubleshooter"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/devops-troubleshooter"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
