"""
Barrel file for technical-debt-analysis skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "technical-debt-analysis"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/technical-debt-analysis"

# Script modules
# from .scripts.analyze_debt import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
