"""
Barrel File Generator - Automates creation of __init__.py files.

This module generates barrel files (index files) for all skills,
eliminating the need for 250+ duplicate __init__.py files.
"""

import json
import os
from pathlib import Path
from typing import List, Dict, Optional
from dataclasses import dataclass


@dataclass
class SkillInfo:
    """Information about a skill for barrel generation."""
    name: str
    path: str
    has_scripts: bool = False
    has_resources: bool = False
    has_examples: bool = False
    exports: List[str] = None

    def __post_init__(self):
        if self.exports is None:
            self.exports = []


class BarrelGenerator:
    """
    Generates barrel files for Global Skills.

    Reads skill_registry.json to discover skills and generates
    appropriate __init__.py files with proper exports.
    """

    def __init__(self, skills_root: str, registry_path: Optional[str] = None):
        """
        Initialize the barrel generator.

        Args:
            skills_root: Root directory containing all skills
            registry_path: Path to skill_registry.json (optional)
        """
        self.skills_root = Path(skills_root)
        self.registry_path = registry_path or self.skills_root / "skill_registry.json"
        self.skills: List[SkillInfo] = []

    def load_registry(self) -> List[Dict]:
        """Load skill registry from JSON file."""
        if not self.registry_path.exists():
            return []

        with open(self.registry_path, "r") as f:
            return json.load(f)

    def discover_skills(self) -> List[SkillInfo]:
        """Discover all skills from registry and filesystem."""
        skills = []

        # Load from registry if available
        registry_skills = self.load_registry()
        for skill_data in registry_skills:
            skill_name = skill_data.get("name", "")
            if not skill_name or skill_name.startswith("Skill #"):
                continue

            skill_path = self.skills_root / skill_name
            if skill_path.exists():
                info = SkillInfo(
                    name=skill_name,
                    path=str(skill_path),
                    has_scripts=(skill_path / "scripts").exists(),
                    has_resources=(skill_path / "resources").exists(),
                    has_examples=(skill_path / "examples").exists(),
                )
                skills.append(info)

        self.skills = skills
        return skills

    def generate_skill_barrel(self, skill: SkillInfo) -> str:
        """Generate barrel file content for a single skill."""
        lines = [
            f'"""',
            f'Barrel file for {skill.name} skill.',
            f'',
            f'This file is auto-generated. Do not edit manually.',
            f'Generated by: src/core/barrel_generator.py',
            f'"""',
            f'',
            f'# Skill metadata',
            f'__skill_name__ = "{skill.name}"',
            f'__skill_path__ = "{skill.path}"',
            f'',
        ]

        # Add script exports if scripts directory exists
        if skill.has_scripts:
            scripts_path = Path(skill.path) / "scripts"
            script_modules = []

            for py_file in scripts_path.glob("*.py"):
                if py_file.name.startswith("_"):
                    continue
                module_name = py_file.stem
                script_modules.append(module_name)

            if script_modules:
                lines.extend([
                    "# Script modules",
                ])
                for module in sorted(script_modules):
                    lines.append(f"# from .scripts.{module} import *")
                lines.append("")

        # Add exports
        lines.extend([
            "# Public API",
            f'__all__ = [',
            f'    "__skill_name__",',
            f'    "__skill_path__",',
        ])

        if skill.exports:
            for export in skill.exports:
                lines.append(f'    "{export}",')

        lines.extend([
            "]",
            "",
        ])

        return "\n".join(lines)

    def generate_root_barrel(self) -> str:
        """Generate the root __init__.py for global_skills."""
        lines = [
            '"""',
            'Global Skills Package - Root barrel file.',
            '',
            'This package contains all Global Skills for THE DUDE.',
            'Auto-generated barrel file.',
            '"""',
            '',
            '# Import core components',
            'from src.core import (',
            '    SkillBase,',
            '    SkillResult,',
            '    SkillStatus,',
            '    SkillEngineInterface,',
            '    PlaybookEngineInterface,',
            ')',
            '',
            '# Package metadata',
            '__version__ = "2.0.0"',
            '__author__ = "THE DUDE Team"',
            '',
            '# Expose core classes',
            '__all__ = [',
            '    "SkillBase",',
            '    "SkillResult",',
            '    "SkillStatus",',
            '    "SkillEngineInterface",',
            '    "PlaybookEngineInterface",',
            ']',
            '',
        ]

        return "\n".join(lines)

    def generate_skills_barrel(self) -> str:
        """Generate the skills directory barrel file."""
        lines = [
            '"""',
            'Skills barrel file - exports all available skills.',
            '',
            'Auto-generated. Do not edit manually.',
            '"""',
            '',
            '# Skill discovery',
            'def list_skills():',
            '    """Return list of all available skill names."""',
            '    return [',
        ]

        for skill in sorted(self.skills, key=lambda s: s.name):
            lines.append(f'        "{skill.name}",')

        lines.extend([
            '    ]',
            '',
            '# Skill metadata access',
            'def get_skill_info(skill_name: str):',
            '    """Get information about a specific skill."""',
            '    skill_map = {',
        ])

        for skill in sorted(self.skills, key=lambda s: s.name):
            lines.append(f'        "{skill.name}": {{')
            lines.append(f'            "name": "{skill.name}",')
            lines.append(f'            "path": "{skill.path}",')
            lines.append(f'            "has_scripts": {skill.has_scripts},')
            lines.append(f'            "has_resources": {skill.has_resources},')
            lines.append(f'            "has_examples": {skill.has_examples},')
            lines.append(f'        }},')

        lines.extend([
            '    }',
            '    return skill_map.get(skill_name)',
            '',
            '__all__ = ["list_skills", "get_skill_info"]',
            '',
        ])

        return "\n".join(lines)

    def write_barrel(self, path: Path, content: str) -> bool:
        """Write barrel file to disk."""
        try:
            with open(path, "w") as f:
                f.write(content)
            return True
        except Exception as e:
            print(f"Error writing {path}: {e}")
            return False

    def generate_all(self, dry_run: bool = False) -> Dict[str, bool]:
        """
        Generate all barrel files.

        Args:
            dry_run: If True, don't actually write files

        Returns:
            Dict mapping file paths to success status
        """
        results = {}

        # Discover skills
        self.discover_skills()
        print(f"Discovered {len(self.skills)} skills")

        # Generate root barrel
        root_barrel = self.skills_root / "__init__.py"
        content = self.generate_root_barrel()
        if dry_run:
            print(f"Would write: {root_barrel}")
        else:
            results[str(root_barrel)] = self.write_barrel(root_barrel, content)

        # Generate individual skill barrels
        for skill in self.skills:
            skill_init = Path(skill.path) / "__init__.py"
            content = self.generate_skill_barrel(skill)
            if dry_run:
                print(f"Would write: {skill_init}")
            else:
                results[str(skill_init)] = self.write_barrel(skill_init, content)

        return results


# Convenience function
def generate_barrel_files(skills_root: str, dry_run: bool = False) -> Dict[str, bool]:
    """
    Generate all barrel files for the skills directory.

    Args:
        skills_root: Path to the global_skills directory
        dry_run: If True, only print what would be done

    Returns:
        Dictionary of file paths and their success status
    """
    generator = BarrelGenerator(skills_root)
    return generator.generate_all(dry_run=dry_run)


if __name__ == "__main__":
    import sys

    skills_root = sys.argv[1] if len(sys.argv) > 1 else "."
    dry_run = "--dry-run" in sys.argv

    results = generate_barrel_files(skills_root, dry_run=dry_run)

    if not dry_run:
        success = sum(1 for v in results.values() if v)
        total = len(results)
        print(f"\nGenerated {success}/{total} barrel files")
