"""
Barrel file for prompt-optimizer-dspy skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "prompt-optimizer-dspy"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/prompt-optimizer-dspy"

# Script modules
# from .scripts.compile_agent import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
