"""
Barrel file for detect-duplicate-files skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "detect-duplicate-files"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/detect-duplicate-files"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
