"""
Barrel file for error-handling-patterns skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "error-handling-patterns"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/error-handling-patterns"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
