"""
Barrel file for infrastructure-core skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "infrastructure-core"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/infrastructure-core"

# Script modules
# from .scripts.common import *
# from .scripts.config import *
# from .scripts.migration_helper import *
# from .scripts.redis_infra import *
# from .scripts.redis_service import *
# from .scripts.supabase_infra import *
# from .scripts.supabase_service import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
