"""
Barrel file for ai-engineer skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "ai-engineer"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/ai-engineer"

# Script modules
# from .scripts.circuit_breaker import *
# from .scripts.model_recommendations import *
# from .scripts.nvidia_config import *
# from .scripts.nvidia_nim_client import *
# from .scripts.test_all_components import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
