"""
Barrel file for vector-index-tuning skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "vector-index-tuning"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/vector-index-tuning"

# Script modules
# from .scripts.tune_business_index import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
