"""
Barrel file for brand-identity skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "brand-identity"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/brand-identity"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
