"""
Barrel file for api-endpoint-tester skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "api-endpoint-tester"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/api-endpoint-tester"

# Script modules
# from .scripts.main import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
