"""
Barrel file for docs-technical-writer skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "docs-technical-writer"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/docs-technical-writer"

# Script modules
# from .scripts.generate_project_docs import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
