"""
Barrel file for git-workflow-hardener skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "git-workflow-hardener"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/git-workflow-hardener"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
