"""
Barrel file for memory-systems skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "memory-systems"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/memory-systems"

# Script modules
# from .scripts.index import *
# from .scripts.knowledge_graph import *
# from .scripts.memory_system import *
# from .scripts.vector_store import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
