"""
Barrel file for agentic-stress-tester skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "agentic-stress-tester"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/agentic-stress-tester"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
