"""
Barrel file for secrets-vault-orchestrator skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "secrets-vault-orchestrator"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/secrets-vault-orchestrator"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
