"""
Barrel file for environment-cleanup-specialist skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "environment-cleanup-specialist"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/environment-cleanup-specialist"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
