"""
Barrel file for subagent-driven-development skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "subagent-driven-development"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/subagent-driven-development"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
