"""
Barrel file for google-slides-visual-creator skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "google-slides-visual-creator"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/google-slides-visual-creator"

# Script modules
# from .scripts.create_deck import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
