"""
Barrel file for legacy-modernizer skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "legacy-modernizer"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/legacy-modernizer"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
