"""
Barrel file for code-modularity-architect skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "code-modularity-architect"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/code-modularity-architect"

# Script modules
# from .scripts.main import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
