"""
Barrel file for acceptance-criteria-guardian skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "acceptance-criteria-guardian"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/acceptance-criteria-guardian"

# Script modules
# from .scripts.validate_ac import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
