"""
Barrel file for master-rag-2026 skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "master-rag-2026"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/master-rag-2026"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
