"""
Barrel file for latency-optimizer skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "latency-optimizer"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/latency-optimizer"

# Script modules
# from .scripts.main import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
