"""
Barrel file for rag-auto-indexer skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "rag-auto-indexer"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/rag-auto-indexer"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
