"""
Barrel file for telegram-mini-app skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "telegram-mini-app"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/telegram-mini-app"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
