"""
Barrel file for database-performance-tuner skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "database-performance-tuner"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/database-performance-tuner"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
