"""
Barrel file for semantic-code-navigator skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "semantic-code-navigator"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/semantic-code-navigator"

# Script modules
# from .scripts.code_nav import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
