"""
Barrel file for cost-control skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "cost-control"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/cost-control"

# Script modules
# from .scripts.example_skill_cost_usage import *
# from .scripts.mcp_cost_controller import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
