"""
Barrel file for neural-architecture-optimizer skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "neural-architecture-optimizer"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/neural-architecture-optimizer"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
