"""
Barrel file for stripe-integration skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "stripe-integration"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/stripe-integration"

# Script modules
# from .scripts.create_stripe_checkout import *
# from .scripts.main import *
# from .scripts.webhook_listener import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
