"""
Barrel file for supabase-admin-tool skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "supabase-admin-tool"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/supabase-admin-tool"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
