"""
Barrel file for codebase-navigator skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "codebase-navigator"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/codebase-navigator"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
