"""
Barrel file for mcp-vetting-guard skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "mcp-vetting-guard"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/mcp-vetting-guard"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
