"""
Barrel file for skill-registry-manager skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "skill-registry-manager"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/skill-registry-manager"

# Script modules
# from .scripts.enrich_skills import *
# from .scripts.validate_skill_schema import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
