"""
Barrel file for visual-learning-engine skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "visual-learning-engine"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/visual-learning-engine"

# Script modules
# from .scripts.visual_qa_audit import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
