"""
Barrel file for gemini-skill-creator skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "gemini-skill-creator"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/gemini-skill-creator"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
