"""
Barrel file for corporate-health-auditor skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "corporate-health-auditor"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/corporate-health-auditor"

# Script modules
# from .scripts.audit import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
