"""
Barrel file for blast-radius-analyst skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "blast-radius-analyst"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/blast-radius-analyst"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
