"""
Barrel file for docker-hub-autonomous skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "docker-hub-autonomous"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/docker-hub-autonomous"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
