"""
Barrel file for infrastructure-as-code-expert skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "infrastructure-as-code-expert"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/infrastructure-as-code-expert"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
