"""
Barrel file for data-quality-frameworks skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "data-quality-frameworks"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/data-quality-frameworks"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
