"""
Barrel file for git-advanced-workflows skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "git-advanced-workflows"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/git-advanced-workflows"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
