"""
Barrel file for python-patterns skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "python-patterns"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/python-patterns"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
