"""
Barrel file for meta-learning-engine skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "meta-learning-engine"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/meta-learning-engine"

# Script modules
# from .scripts.optimizer import *

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
