"""
Barrel file for instruction-compressor skill.

This file is auto-generated. Do not edit manually.
Generated by: src/core/barrel_generator.py
"""

# Skill metadata
__skill_name__ = "instruction-compressor"
__skill_path__ = "/Users/mauroociappina/Desktop/TheDude/global_skills/instruction-compressor"

# Public API
__all__ = [
    "__skill_name__",
    "__skill_path__",
]
